name: vadasada
description: Mimsoft Ecommerce Solution.


version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  random_pk: any
  http: ^0.13.0
  shimmer: ^2.0.0
  transparent_image: ^2.0.0
  flutter_slidable: ^1.3.0
  flutter_rating: ^0.0.2
  localstorage: ^4.0.0+1
  loading_overlay: ^0.3.0
  flutter_html: ^3.0.0-alpha.5
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.3
  flutter_launcher_icons: ^0.9.3
  package_info_plus: ^1.4.2
  auto_size_text: ^3.0.0
  connectivity: 3.0.6
  sliver_tools: ^0.2.5
  dropdown_search: ^5.0.2
  change_app_package_name: ^1.0.0
  marquee: ^2.2.0
  sweetalert: ^0.0.1
  velocity_x: ^3.4.0
  dotted_border: ^2.0.0
  file_picker: ^4.6.1
  open_file: ^3.2.1
  flutter_phone_direct_caller: ^2.1.1
  multi_image_picker: ^4.8.0
  provider: ^6.0.3
  modal_progress_hud: ^0.1.3
  image_picker: ^0.8.4+1
  path_provider: ^2.0.11
  card_settings: ^3.0.1
  image_cropper: ^2.0.3
  fdottedline: ^1.0.1
  path: ^1.8.0
  badges: ^2.0.1
  uni_links: ^0.5.1
  share_plus: ^4.0.9
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.7
  firebase_dynamic_links: ^4.0.7
  cloud_firestore: ^3.1.9
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11

flutter_icons:
  ios: true
  # android: "launcher_icon"
  image_path: "assets/appIcon/icon.jpg"
  # image_path_ios: "assets/launcher/icon.png"
  # image_path_android: "assets/launcher/icon.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family : Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight : 600
    - family : Berlin
      fonts:
        - asset: assets/font/BRLNSDB.TTF
          weight: 700
    - family : Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight : 600

  assets:
    - assets/mainSlider/
    - assets/img/
    - assets/imgIllustration/